### ISSUE TITLE
Needed: overview for custom_updater... how to/instructions

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#22]
**Is your feature request related to a problem? Please describe.**
a bit of both, no bug!
Since there's not much documentation on rather an important detail, please let me ask here (tried the community, but no response yet)

How to configure the custom_card tracker (on Hassio Non lovelace). 

As of now, I have 2 sensors in the frontend displaying rather unmeaningful states, More-Info is alright.
That is, on the custom component, where I was able to set several components to track.

Not so on the custom_cards.

**Describe the solution you'd like**
Some instruction and examples how to configure

**Describe alternatives you've considered**

What would be really cool: a list of currently available cards and components to simply copy into the configuration. Not that many cards and CC' yet , so hope thats an option?

**Additional context**

![schermafbeelding 2018-09-13 om 16 48 46](https://user-images.githubusercontent.com/33354141/45496080-ed4aed00-b774-11e8-840f-2f673933e403.jpg)
![schermafbeelding 2018-09-13 om 16 48 52](https://user-images.githubusercontent.com/33354141/45496082-ed4aed00-b774-11e8-93a5-cafc2f0da78b.jpg)

```
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
  show_installable: True
```

**Comment by ludeeus** [comment]
Thanks for this, and I agree I need to add some more options and details for non lovelace users.
Will try to have a look at some options during this weekend.

**Comment by ludeeus** [comment]
The first step are now in place https://github.com/custom-components/custom_updater/releases/tag/2.7.0

**Comment by ludeeus** [comment]
@Mariusthvdb Can you check out version 3.0.0 and see if that are more suited for users without Lovelace?

**Comment by ludeeus** [comment]
Yes and no.
For this version I expect that, and I'm unsure about if I want to do remove them

**Comment by ludeeus** [comment]
Yes, by default the component has 2 "repos", you you want more then that you still need to add them.
The "repos" that are default are:
https://github.com/custom-components/information/blob/master/repos.json
https://github.com/custom-cards/information/blob/master/repos.json

**Comment by Mariusthvdb** [comment]
not really sure what the change is here? I still see the complete list in components.

btw, does the card checker look in a dedicated folder? Ive got my lovelace cards in /local/custom-ui/lovelace but the sensor.custom_card_tracker isn't created. I have no repos defined, so I believed it would read the default repos you posted above?

**Comment by ludeeus** [comment]
nvm... I see now that you have `show_installable: True`, that will still show all :)

There was a change now, it only tracks components by default, if you want to track cards and/or python_scripts, you need to enable that in your config.

<https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-track>

**Comment by Mariusthvdb** [comment]
have all installed now, but no difference in state. will check tomorrow.

omt: if I try to customize the sensor using my default setup:

```
customize:
    sensor.custom_component_tracker:
      templates:
        icon: >
          if (state > 0) return 'mdi:cloud-upload';
          return 'mdi:cloud-search';
        icon_color: >
          if (state > 0) return 'rgb(251, 210, 41)';
          return 'grey';
```

nothing happens. Ive tried

```
customize:
    sensor.custom_component_tracker:
      templates:
        icon: >
          if (state > '0') return 'mdi:cloud-upload';
          return 'mdi:cloud-search';
        icon_color: >
          if (state > '0') return 'rgb(251, 210, 41)';
          return 'grey';
```

but still no change in the frontend. 

Pleas let me ask what the state is? string, int, or? I cant seem to get it right.

**Comment by ludeeus** [comment]
The difference would not be in the state.
If you set `show_installable` to `False` (or remove it) you would see a lot less in the attributes.

And if you enable `cards` and `components` under `track` you will see another sensor.

The sensor value is an int, but it is not explicit defined in the code, so HA might interpret it as a string..

I have no idea about what you are trying do do in your examples :P 
This give me a True/False response in the template editor:
```yaml
{{ states('sensor.custom_component_tracker') > '0' }}
```

**Comment by Mariusthvdb** [comment]
HI,
thx!
so show_installable actually is show_all_available, and not show the updates available?
Iif I set it to False, the sensor will show only the available updates for my installed components?
Because thats what I was trying to establish:
have the sensor check which components I have installed, and check for available updates.

```
I have no idea about what you are trying do do in your examples :P
This give me a True/False response in the template editor:

{{ states('sensor.custom_component_tracker') > '0' }}
```

with this customization I am setting an icon and icon_color depending on the state, and have the frontend give visual feedback about the state, instead of the default and rather meaningless eye...

like this:

![schermafbeelding 2018-09-30 om 09 14 43](https://user-images.githubusercontent.com/33354141/46254541-5464e300-c491-11e8-81b3-754d164865be.jpg)
![schermafbeelding 2018-09-30 om 09 14 51](https://user-images.githubusercontent.com/33354141/46254542-54fd7980-c491-11e8-9afd-dd10bf620c67.jpg)

wont work yet, I think because the sensors are made in the Python script, id have to set these there:

example:

```
whichIcon = familyIcon[count_home] if count_home <= 3 else familyIcon[-1]
icon_color = familyColor[count_home%len(familyColor)]

hass.states.set('sensor.family_home', count_home, {
    'custom_ui_state_card': 'state-card-custom-ui',
    'friendly_name': 'Family Home?',
    'home': ', '.join(home),
    'away': ', '.join(away),
    'icon': whichIcon,
    'count_home': count_home,
    'count_away': count_away,
    'family_count': familyCount,
    'icon_color': icon_color ,
    'show_last_changed': 'true'
     })
```

**Comment by Mariusthvdb** [comment]
can confirm your changes worked for the sensors state to show available updates;

![schermafbeelding 2018-09-30 om 12 11 31](https://user-images.githubusercontent.com/33354141/46256362-23dd7300-c4aa-11e8-92bb-d03db0fa7792.jpg)
![schermafbeelding 2018-09-30 om 12 11 38](https://user-images.githubusercontent.com/33354141/46256368-293abd80-c4aa-11e8-8abb-01bebf80b0cd.jpg)

cool, thx.

**Comment by ludeeus** [comment]
With the launch of version 3x I also moved the documentation for this to the repo wiki, and expanded it a bit, it should now cover your initial "issue" 
"Since there's not much documentation "

<https://github.com/custom-components/custom_updater/wiki/Installation>

**Comment by sendorm** [comment]
After doing the update to 3.1.0 manually. I can't seem to find the components. When I set the  `show_last_changed: true` to see all available components, I see the custom_updater's and sensor.aftership's statuses as n/a. I've both those components installed and working btw. 
I've also have the track for components and cards enabled. I have hass version 0.79.0.
Thank you.

**Comment by sendorm** [comment]
Wrong copy paste. I’ve corrected the original post. Ok, I’ll create a new issue. Thanks.

**Comment by ludeeus** [comment]
Still not the same issue as OP @sendorm ;)
But it looks similar to <https://github.com/custom-cards/tracker-card/issues/21>

**Comment by sendorm** [comment]
Yes, I knew it was not the same issue as the OP. That's why I was going to create a new issue :) The one you suggest seems to be the same case, thanks for directing me to the correct issue :) I'll be following that one.

**Comment by ludeeus** [comment]
Closing this issue, further customization from this will be done in <https://github.com/custom-components/custom_updater/issues/35>
